//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Collections.ObjectModel;

namespace zVirtualScenesModel
{
    
    public partial class builtin_commands : INotifyPropertyChanged
    {
    	public event PropertyChangedEventHandler PropertyChanged;
        protected void NotifyPropertyChanged(string name)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(name));
            }
        }
    
        public builtin_commands()
        {
            this.builtin_command_options = new ObservableCollection<builtin_command_options>();
            this.builtin_command_que = new ObservableCollection<builtin_command_que>();
        }
    
    	private int _id;
        public int id {
    		get { 
    			return _id;
    		} 
    		set {
    			if (value != _id){
    			    int old = _id;
    				BeforeidChange(old, value);
    				_id = value;
    			    NotifyPropertyChanged("id");
    				AfteridChange(old, value);
    			}
    		}
    	 } 
    
    	partial void BeforeidChange(int oldValue, int newValue);
    	partial void AfteridChange(int oldValue, int newValue);
    
    	private string _name;
        public string name {
    		get { 
    			return _name;
    		} 
    		set {
    			if (value != _name){
    			    string old = _name;
    				BeforenameChange(old, value);
    				_name = value;
    			    NotifyPropertyChanged("name");
    				AfternameChange(old, value);
    			}
    		}
    	 } 
    
    	partial void BeforenameChange(string oldValue, string newValue);
    	partial void AfternameChange(string oldValue, string newValue);
    
    	private string _friendly_name;
        public string friendly_name {
    		get { 
    			return _friendly_name;
    		} 
    		set {
    			if (value != _friendly_name){
    			    string old = _friendly_name;
    				Beforefriendly_nameChange(old, value);
    				_friendly_name = value;
    			    NotifyPropertyChanged("friendly_name");
    				Afterfriendly_nameChange(old, value);
    			}
    		}
    	 } 
    
    	partial void Beforefriendly_nameChange(string oldValue, string newValue);
    	partial void Afterfriendly_nameChange(string oldValue, string newValue);
    
    	private int _arg_data_type;
        public int arg_data_type {
    		get { 
    			return _arg_data_type;
    		} 
    		set {
    			if (value != _arg_data_type){
    			    int old = _arg_data_type;
    				Beforearg_data_typeChange(old, value);
    				_arg_data_type = value;
    			    NotifyPropertyChanged("arg_data_type");
    				Afterarg_data_typeChange(old, value);
    			}
    		}
    	 } 
    
    	partial void Beforearg_data_typeChange(int oldValue, int newValue);
    	partial void Afterarg_data_typeChange(int oldValue, int newValue);
    
    	private string _custom_data1;
        public string custom_data1 {
    		get { 
    			return _custom_data1;
    		} 
    		set {
    			if (value != _custom_data1){
    			    string old = _custom_data1;
    				Beforecustom_data1Change(old, value);
    				_custom_data1 = value;
    			    NotifyPropertyChanged("custom_data1");
    				Aftercustom_data1Change(old, value);
    			}
    		}
    	 } 
    
    	partial void Beforecustom_data1Change(string oldValue, string newValue);
    	partial void Aftercustom_data1Change(string oldValue, string newValue);
    
    	private string _custom_data2;
        public string custom_data2 {
    		get { 
    			return _custom_data2;
    		} 
    		set {
    			if (value != _custom_data2){
    			    string old = _custom_data2;
    				Beforecustom_data2Change(old, value);
    				_custom_data2 = value;
    			    NotifyPropertyChanged("custom_data2");
    				Aftercustom_data2Change(old, value);
    			}
    		}
    	 } 
    
    	partial void Beforecustom_data2Change(string oldValue, string newValue);
    	partial void Aftercustom_data2Change(string oldValue, string newValue);
    
    	private string _description;
        public string description {
    		get { 
    			return _description;
    		} 
    		set {
    			if (value != _description){
    			    string old = _description;
    				BeforedescriptionChange(old, value);
    				_description = value;
    			    NotifyPropertyChanged("description");
    				AfterdescriptionChange(old, value);
    			}
    		}
    	 } 
    
    	partial void BeforedescriptionChange(string oldValue, string newValue);
    	partial void AfterdescriptionChange(string oldValue, string newValue);
    
    	private bool _show_on_dynamic_obj_list;
        public bool show_on_dynamic_obj_list {
    		get { 
    			return _show_on_dynamic_obj_list;
    		} 
    		set {
    			if (value != _show_on_dynamic_obj_list){
    			    bool old = _show_on_dynamic_obj_list;
    				Beforeshow_on_dynamic_obj_listChange(old, value);
    				_show_on_dynamic_obj_list = value;
    			    NotifyPropertyChanged("show_on_dynamic_obj_list");
    				Aftershow_on_dynamic_obj_listChange(old, value);
    			}
    		}
    	 } 
    
    	partial void Beforeshow_on_dynamic_obj_listChange(bool oldValue, bool newValue);
    	partial void Aftershow_on_dynamic_obj_listChange(bool oldValue, bool newValue);
    
    	private string _help;
        public string help {
    		get { 
    			return _help;
    		} 
    		set {
    			if (value != _help){
    			    string old = _help;
    				BeforehelpChange(old, value);
    				_help = value;
    			    NotifyPropertyChanged("help");
    				AfterhelpChange(old, value);
    			}
    		}
    	 } 
    
    	partial void BeforehelpChange(string oldValue, string newValue);
    	partial void AfterhelpChange(string oldValue, string newValue);
    
    	private Nullable<int> _sort_order;
        public Nullable<int> sort_order {
    		get { 
    			return _sort_order;
    		} 
    		set {
    			if (value != _sort_order){
    			    Nullable<int> old = _sort_order;
    				Beforesort_orderChange(old, value);
    				_sort_order = value;
    			    NotifyPropertyChanged("sort_order");
    				Aftersort_orderChange(old, value);
    			}
    		}
    	 } 
    
    	partial void Beforesort_orderChange(Nullable<int> oldValue, Nullable<int> newValue);
    	partial void Aftersort_orderChange(Nullable<int> oldValue, Nullable<int> newValue);
    
    
    	private ObservableCollection<builtin_command_options> _builtin_command_options;
        public virtual ObservableCollection<builtin_command_options> builtin_command_options {
    		get { 
    			return _builtin_command_options;
    		} 
    		set {
    			if (value != _builtin_command_options){
    			    ObservableCollection<builtin_command_options> old = _builtin_command_options;
    				Beforebuiltin_command_optionsChange(old, value);
    				_builtin_command_options = value;
    			    NotifyPropertyChanged("builtin_command_options");
    				Afterbuiltin_command_optionsChange(old, value);
    			}
    		}
    	 } 
    
    	partial void Beforebuiltin_command_optionsChange(ObservableCollection<builtin_command_options> oldValue, ObservableCollection<builtin_command_options> newValue);
    	partial void Afterbuiltin_command_optionsChange(ObservableCollection<builtin_command_options> oldValue, ObservableCollection<builtin_command_options> newValue);
    
    	private ObservableCollection<builtin_command_que> _builtin_command_que;
        public virtual ObservableCollection<builtin_command_que> builtin_command_que {
    		get { 
    			return _builtin_command_que;
    		} 
    		set {
    			if (value != _builtin_command_que){
    			    ObservableCollection<builtin_command_que> old = _builtin_command_que;
    				Beforebuiltin_command_queChange(old, value);
    				_builtin_command_que = value;
    			    NotifyPropertyChanged("builtin_command_que");
    				Afterbuiltin_command_queChange(old, value);
    			}
    		}
    	 } 
    
    	partial void Beforebuiltin_command_queChange(ObservableCollection<builtin_command_que> oldValue, ObservableCollection<builtin_command_que> newValue);
    	partial void Afterbuiltin_command_queChange(ObservableCollection<builtin_command_que> oldValue, ObservableCollection<builtin_command_que> newValue);
    }
}
