//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Collections.ObjectModel;

namespace zVirtualScenesModel
{
    
    public partial class builtin_command_que : INotifyPropertyChanged
    {
    	public event PropertyChangedEventHandler PropertyChanged;
        protected void NotifyPropertyChanged(string name)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(name));
            }
        }
    
    
    	private int _id;
        public int id {
    		get { 
    			return _id;
    		} 
    		set {
    			if (value != _id){
    			    int old = _id;
    				BeforeidChange(old, value);
    				_id = value;
    			    NotifyPropertyChanged("id");
    				AfteridChange(old, value);
    			}
    		}
    	 } 
    
    	partial void BeforeidChange(int oldValue, int newValue);
    	partial void AfteridChange(int oldValue, int newValue);
    
    	private string _arg;
        public string arg {
    		get { 
    			return _arg;
    		} 
    		set {
    			if (value != _arg){
    			    string old = _arg;
    				BeforeargChange(old, value);
    				_arg = value;
    			    NotifyPropertyChanged("arg");
    				AfterargChange(old, value);
    			}
    		}
    	 } 
    
    	partial void BeforeargChange(string oldValue, string newValue);
    	partial void AfterargChange(string oldValue, string newValue);
    
    	private int _builtin_command_id;
        public int builtin_command_id {
    		get { 
    			return _builtin_command_id;
    		} 
    		set {
    			if (value != _builtin_command_id){
    			    int old = _builtin_command_id;
    				Beforebuiltin_command_idChange(old, value);
    				_builtin_command_id = value;
    			    NotifyPropertyChanged("builtin_command_id");
    				Afterbuiltin_command_idChange(old, value);
    			}
    		}
    	 } 
    
    	partial void Beforebuiltin_command_idChange(int oldValue, int newValue);
    	partial void Afterbuiltin_command_idChange(int oldValue, int newValue);
    
    
    	private builtin_commands _builtin_commands;
        public virtual builtin_commands builtin_commands {
    		get { 
    			return _builtin_commands;
    		} 
    		set {
    			if (value != _builtin_commands){
    			    builtin_commands old = _builtin_commands;
    				Beforebuiltin_commandsChange(old, value);
    				_builtin_commands = value;
    			    NotifyPropertyChanged("builtin_commands");
    				Afterbuiltin_commandsChange(old, value);
    			}
    		}
    	 } 
    
    	partial void Beforebuiltin_commandsChange(builtin_commands oldValue, builtin_commands newValue);
    	partial void Afterbuiltin_commandsChange(builtin_commands oldValue, builtin_commands newValue);
    }
}
