//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zvsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_property_values
    {
        public int id { get; set; }
        public int device_id { get; set; }
        public int device_property_id { get; set; }
        public string value { get; set; }
    
        public virtual device_propertys device_propertys { get; set; }
        public virtual device device { get; set; }
    }
}
