//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Collections.ObjectModel;

namespace zVirtualScenesModel
{
    
    public partial class device_types : INotifyPropertyChanged
    {
    	public event PropertyChangedEventHandler PropertyChanged;
         protected void NotifyPropertyChanged(string name)
            {
                onBeforePropertyChanged(name);
                if (PropertyChanged != null)
                {
                    PropertyChanged(this, new PropertyChangedEventArgs(name));
                }
                onAfterPropertyChanged(name);
            }
         partial void onBeforePropertyChanged(string name);
         partial void onAfterPropertyChanged(string name);
    
        public device_types()
        {
            this.device_type_commands = new ObservableCollection<device_type_commands>();
            this.devices = new ObservableCollection<device>();
        }
    
    	private int _id;
        public int id {
    		get { 
    			return _id;
    		} 
    		set {
    			if (value != _id){
    				_id = value;
    			    NotifyPropertyChanged("id");
    			}
    		}
    	 }
    
    	private int _plugin_id;
        public int plugin_id {
    		get { 
    			return _plugin_id;
    		} 
    		set {
    			if (value != _plugin_id){
    				_plugin_id = value;
    			    NotifyPropertyChanged("plugin_id");
    			}
    		}
    	 }
    
    	private string _name;
        public string name {
    		get { 
    			return _name;
    		} 
    		set {
    			if (value != _name){
    				_name = value;
    			    NotifyPropertyChanged("name");
    			}
    		}
    	 }
    
    	private bool _show_in_list;
        public bool show_in_list {
    		get { 
    			return _show_in_list;
    		} 
    		set {
    			if (value != _show_in_list){
    				_show_in_list = value;
    			    NotifyPropertyChanged("show_in_list");
    			}
    		}
    	 }
    
    	private string _friendly_name;
        public string friendly_name {
    		get { 
    			return _friendly_name;
    		} 
    		set {
    			if (value != _friendly_name){
    				_friendly_name = value;
    			    NotifyPropertyChanged("friendly_name");
    			}
    		}
    	 }
    
    
    	private ObservableCollection<device_type_commands> _device_type_commands;
        public virtual ObservableCollection<device_type_commands> device_type_commands {
    		get { 
    			return _device_type_commands;
    		} 
    		set {
    			if (value != _device_type_commands){
    				_device_type_commands = value;
    			    NotifyPropertyChanged("device_type_commands");
    			}
    		}
    	 }
    
    	private plugin _plugin;
        public virtual plugin plugin {
    		get { 
    			return _plugin;
    		} 
    		set {
    			if (value != _plugin){
    				_plugin = value;
    			    NotifyPropertyChanged("plugin");
    			}
    		}
    	 }
    
    	private ObservableCollection<device> _devices;
        public virtual ObservableCollection<device> devices {
    		get { 
    			return _devices;
    		} 
    		set {
    			if (value != _devices){
    				_devices = value;
    			    NotifyPropertyChanged("devices");
    			}
    		}
    	 }
    }
}
