//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zvsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_values
    {
        public device_values()
        {
            this.device_value_triggers = new HashSet<device_value_triggers>();
        }
    
        public int id { get; set; }
        public int device_id { get; set; }
        public string value_id { get; set; }
        public string label_name { get; set; }
        public string genre { get; set; }
        public string index2 { get; set; }
        public string type { get; set; }
        public string commandClassId { get; set; }
        public string value2 { get; set; }
        public bool read_only { get; set; }
    
        public virtual ICollection<device_value_triggers> device_value_triggers { get; set; }
        public virtual device device { get; set; }
    }
}
