//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zVirtualScenesModel
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    
    public partial class device_propertys
    {
        public device_propertys()
        {
            this.device_property_options = new ObservableCollection<device_property_options>();
            this.device_property_values = new ObservableCollection<device_property_values>();
        }
    
        public int id { get; set; }
        public string friendly_name { get; set; }
        public string name { get; set; }
        public string default_value { get; set; }
        public int value_data_type { get; set; }
    
        public virtual ObservableCollection<device_property_options> device_property_options { get; set; }
        public virtual ObservableCollection<device_property_values> device_property_values { get; set; }
    }
}
