//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Collections.ObjectModel;

namespace zVirtualScenesModel
{
    
    public partial class device_type_command_que : INotifyPropertyChanged
    {
    	public event PropertyChangedEventHandler PropertyChanged;
         protected void NotifyPropertyChanged(string name)
            {
                onBeforePropertyChanged(name);
                if (PropertyChanged != null)
                {
                    PropertyChanged(this, new PropertyChangedEventArgs(name));
                }
                onAfterPropertyChanged(name);
            }
         partial void onBeforePropertyChanged(string name);
         partial void onAfterPropertyChanged(string name);
    
    
    	private int _id;
        public int id {
    		get { 
    			return _id;
    		} 
    		set {
    			if (value != _id){
    				_id = value;
    			    NotifyPropertyChanged("id");
    			}
    		}
    	 }
    
    	private int _device_type_command_id;
        public int device_type_command_id {
    		get { 
    			return _device_type_command_id;
    		} 
    		set {
    			if (value != _device_type_command_id){
    				_device_type_command_id = value;
    			    NotifyPropertyChanged("device_type_command_id");
    			}
    		}
    	 }
    
    	private int _device_id;
        public int device_id {
    		get { 
    			return _device_id;
    		} 
    		set {
    			if (value != _device_id){
    				_device_id = value;
    			    NotifyPropertyChanged("device_id");
    			}
    		}
    	 }
    
    	private string _arg;
        public string arg {
    		get { 
    			return _arg;
    		} 
    		set {
    			if (value != _arg){
    				_arg = value;
    			    NotifyPropertyChanged("arg");
    			}
    		}
    	 }
    
    
    	private device _device;
        public virtual device device {
    		get { 
    			return _device;
    		} 
    		set {
    			if (value != _device){
    				_device = value;
    			    NotifyPropertyChanged("device");
    			}
    		}
    	 }
    
    	private device_type_commands _device_type_commands;
        public virtual device_type_commands device_type_commands {
    		get { 
    			return _device_type_commands;
    		} 
    		set {
    			if (value != _device_type_commands){
    				_device_type_commands = value;
    			    NotifyPropertyChanged("device_type_commands");
    			}
    		}
    	 }
    }
}
