//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Collections.ObjectModel;

namespace zVirtualScenesModel
{
    
    public partial class group_devices : INotifyPropertyChanged
    {
    	public event PropertyChangedEventHandler PropertyChanged;
        protected void NotifyPropertyChanged(string name)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(name));
            }
        }
    
    
    	private int _device_id;
        public int device_id {
    		get { 
    			return _device_id;
    		} 
    		set {
    			if (value != _device_id){
    			    int old = _device_id;
    				Beforedevice_idChange(old, value);
    				_device_id = value;
    			    NotifyPropertyChanged("device_id");
    				Afterdevice_idChange(old, value);
    			}
    		}
    	 } 
    
    	partial void Beforedevice_idChange(int oldValue, int newValue);
    	partial void Afterdevice_idChange(int oldValue, int newValue);
    
    	private int _id;
        public int id {
    		get { 
    			return _id;
    		} 
    		set {
    			if (value != _id){
    			    int old = _id;
    				BeforeidChange(old, value);
    				_id = value;
    			    NotifyPropertyChanged("id");
    				AfteridChange(old, value);
    			}
    		}
    	 } 
    
    	partial void BeforeidChange(int oldValue, int newValue);
    	partial void AfteridChange(int oldValue, int newValue);
    
    	private int _group_id;
        public int group_id {
    		get { 
    			return _group_id;
    		} 
    		set {
    			if (value != _group_id){
    			    int old = _group_id;
    				Beforegroup_idChange(old, value);
    				_group_id = value;
    			    NotifyPropertyChanged("group_id");
    				Aftergroup_idChange(old, value);
    			}
    		}
    	 } 
    
    	partial void Beforegroup_idChange(int oldValue, int newValue);
    	partial void Aftergroup_idChange(int oldValue, int newValue);
    
    
    	private device _device;
        public virtual device device {
    		get { 
    			return _device;
    		} 
    		set {
    			if (value != _device){
    			    device old = _device;
    				BeforedeviceChange(old, value);
    				_device = value;
    			    NotifyPropertyChanged("device");
    				AfterdeviceChange(old, value);
    			}
    		}
    	 } 
    
    	partial void BeforedeviceChange(device oldValue, device newValue);
    	partial void AfterdeviceChange(device oldValue, device newValue);
    
    	private group _group;
        public virtual group group {
    		get { 
    			return _group;
    		} 
    		set {
    			if (value != _group){
    			    group old = _group;
    				BeforegroupChange(old, value);
    				_group = value;
    			    NotifyPropertyChanged("group");
    				AftergroupChange(old, value);
    			}
    		}
    	 } 
    
    	partial void BeforegroupChange(group oldValue, group newValue);
    	partial void AftergroupChange(group oldValue, group newValue);
    }
}
