//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Collections.ObjectModel;

namespace zVirtualScenesModel
{
    
    public partial class plugin_settings : INotifyPropertyChanged
    {
    	public event PropertyChangedEventHandler PropertyChanged;
         protected void NotifyPropertyChanged(string name)
            {
                onBeforePropertyChanged(name);
                if (PropertyChanged != null)
                {
                    PropertyChanged(this, new PropertyChangedEventArgs(name));
                }
                onAfterPropertyChanged(name);
            }
         partial void onBeforePropertyChanged(string name);
         partial void onAfterPropertyChanged(string name);
    
        public plugin_settings()
        {
            this.plugin_setting_options = new ObservableCollection<plugin_setting_options>();
        }
    
    	private int _id;
        public int id {
    		get { 
    			return _id;
    		} 
    		set {
    			if (value != _id){
    				_id = value;
    			    NotifyPropertyChanged("id");
    			}
    		}
    	 }
    
    	private int _plugin_id;
        public int plugin_id {
    		get { 
    			return _plugin_id;
    		} 
    		set {
    			if (value != _plugin_id){
    				_plugin_id = value;
    			    NotifyPropertyChanged("plugin_id");
    			}
    		}
    	 }
    
    	private string _friendly_name;
        public string friendly_name {
    		get { 
    			return _friendly_name;
    		} 
    		set {
    			if (value != _friendly_name){
    				_friendly_name = value;
    			    NotifyPropertyChanged("friendly_name");
    			}
    		}
    	 }
    
    	private string _value;
        public string value {
    		get { 
    			return _value;
    		} 
    		set {
    			if (value != _value){
    				_value = value;
    			    NotifyPropertyChanged("value");
    			}
    		}
    	 }
    
    	private int _value_data_type;
        public int value_data_type {
    		get { 
    			return _value_data_type;
    		} 
    		set {
    			if (value != _value_data_type){
    				_value_data_type = value;
    			    NotifyPropertyChanged("value_data_type");
    			}
    		}
    	 }
    
    	private string _description;
        public string description {
    		get { 
    			return _description;
    		} 
    		set {
    			if (value != _description){
    				_description = value;
    			    NotifyPropertyChanged("description");
    			}
    		}
    	 }
    
    	private string _name;
        public string name {
    		get { 
    			return _name;
    		} 
    		set {
    			if (value != _name){
    				_name = value;
    			    NotifyPropertyChanged("name");
    			}
    		}
    	 }
    
    
    	private ObservableCollection<plugin_setting_options> _plugin_setting_options;
        public virtual ObservableCollection<plugin_setting_options> plugin_setting_options {
    		get { 
    			return _plugin_setting_options;
    		} 
    		set {
    			if (value != _plugin_setting_options){
    				_plugin_setting_options = value;
    			    NotifyPropertyChanged("plugin_setting_options");
    			}
    		}
    	 }
    
    	private plugin _plugin;
        public virtual plugin plugin {
    		get { 
    			return _plugin;
    		} 
    		set {
    			if (value != _plugin){
    				_plugin = value;
    			    NotifyPropertyChanged("plugin");
    			}
    		}
    	 }
    }
}
