//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zvsModel
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    
    public partial class plugin_settings
    {
        public plugin_settings()
        {
            this.plugin_setting_options = new ObservableCollection<plugin_setting_options>();
        }
    
        public int id { get; set; }
        public int plugin_id { get; set; }
        public string friendly_name { get; set; }
        public string value { get; set; }
        public int value_data_type { get; set; }
        public string description { get; set; }
        public string name { get; set; }
    
        public virtual ObservableCollection<plugin_setting_options> plugin_setting_options { get; set; }
        public virtual plugin plugin { get; set; }
    }
}
