//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Collections.ObjectModel;

namespace zVirtualScenesModel
{
    
    public partial class plugin : INotifyPropertyChanged
    {
    	public event PropertyChangedEventHandler PropertyChanged;
         protected void NotifyPropertyChanged(string name)
            {
                onBeforePropertyChanged(name);
                if (PropertyChanged != null)
                {
                    PropertyChanged(this, new PropertyChangedEventArgs(name));
                }
                onAfterPropertyChanged(name);
            }
         partial void onBeforePropertyChanged(string name);
         partial void onAfterPropertyChanged(string name);
    
        public plugin()
        {
            this.device_types = new ObservableCollection<device_types>();
            this.plugin_settings = new ObservableCollection<plugin_settings>();
        }
    
    	private int _id;
        public int id {
    		get { 
    			return _id;
    		} 
    		set {
    			if (value != _id){
    				_id = value;
    			    NotifyPropertyChanged("id");
    			}
    		}
    	 }
    
    	private string _friendly_name;
        public string friendly_name {
    		get { 
    			return _friendly_name;
    		} 
    		set {
    			if (value != _friendly_name){
    				_friendly_name = value;
    			    NotifyPropertyChanged("friendly_name");
    			}
    		}
    	 }
    
    	private string _name;
        public string name {
    		get { 
    			return _name;
    		} 
    		set {
    			if (value != _name){
    				_name = value;
    			    NotifyPropertyChanged("name");
    			}
    		}
    	 }
    
    	private bool _enabled;
        public bool enabled {
    		get { 
    			return _enabled;
    		} 
    		set {
    			if (value != _enabled){
    				_enabled = value;
    			    NotifyPropertyChanged("enabled");
    			}
    		}
    	 }
    
    	private string _description;
        public string description {
    		get { 
    			return _description;
    		} 
    		set {
    			if (value != _description){
    				_description = value;
    			    NotifyPropertyChanged("description");
    			}
    		}
    	 }
    
    
    	private ObservableCollection<device_types> _device_types;
        public virtual ObservableCollection<device_types> device_types {
    		get { 
    			return _device_types;
    		} 
    		set {
    			if (value != _device_types){
    				_device_types = value;
    			    NotifyPropertyChanged("device_types");
    			}
    		}
    	 }
    
    	private ObservableCollection<plugin_settings> _plugin_settings;
        public virtual ObservableCollection<plugin_settings> plugin_settings {
    		get { 
    			return _plugin_settings;
    		} 
    		set {
    			if (value != _plugin_settings){
    				_plugin_settings = value;
    			    NotifyPropertyChanged("plugin_settings");
    			}
    		}
    	 }
    }
}
