//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Collections.ObjectModel;

namespace zVirtualScenesModel
{
    
    public partial class plugin_settings : INotifyPropertyChanged
    {
    	public event PropertyChangedEventHandler PropertyChanged;
        protected void NotifyPropertyChanged(string name)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(name));
            }
        }
    
        public plugin_settings()
        {
            this.plugin_setting_options = new ObservableCollection<plugin_setting_options>();
        }
    
    	private int _id;
        public int id {
    		get { 
    			return _id;
    		} 
    		set {
    			if (value != _id){
    			    int old = _id;
    				BeforeidChange(old, value);
    				_id = value;
    			    NotifyPropertyChanged("id");
    				AfteridChange(old, value);
    			}
    		}
    	 } 
    
    	partial void BeforeidChange(int oldValue, int newValue);
    	partial void AfteridChange(int oldValue, int newValue);
    
    	private int _plugin_id;
        public int plugin_id {
    		get { 
    			return _plugin_id;
    		} 
    		set {
    			if (value != _plugin_id){
    			    int old = _plugin_id;
    				Beforeplugin_idChange(old, value);
    				_plugin_id = value;
    			    NotifyPropertyChanged("plugin_id");
    				Afterplugin_idChange(old, value);
    			}
    		}
    	 } 
    
    	partial void Beforeplugin_idChange(int oldValue, int newValue);
    	partial void Afterplugin_idChange(int oldValue, int newValue);
    
    	private string _friendly_name;
        public string friendly_name {
    		get { 
    			return _friendly_name;
    		} 
    		set {
    			if (value != _friendly_name){
    			    string old = _friendly_name;
    				Beforefriendly_nameChange(old, value);
    				_friendly_name = value;
    			    NotifyPropertyChanged("friendly_name");
    				Afterfriendly_nameChange(old, value);
    			}
    		}
    	 } 
    
    	partial void Beforefriendly_nameChange(string oldValue, string newValue);
    	partial void Afterfriendly_nameChange(string oldValue, string newValue);
    
    	private string _value;
        public string value {
    		get { 
    			return _value;
    		} 
    		set {
    			if (value != _value){
    			    string old = _value;
    				BeforevalueChange(old, value);
    				_value = value;
    			    NotifyPropertyChanged("value");
    				AftervalueChange(old, value);
    			}
    		}
    	 } 
    
    	partial void BeforevalueChange(string oldValue, string newValue);
    	partial void AftervalueChange(string oldValue, string newValue);
    
    	private int _value_data_type;
        public int value_data_type {
    		get { 
    			return _value_data_type;
    		} 
    		set {
    			if (value != _value_data_type){
    			    int old = _value_data_type;
    				Beforevalue_data_typeChange(old, value);
    				_value_data_type = value;
    			    NotifyPropertyChanged("value_data_type");
    				Aftervalue_data_typeChange(old, value);
    			}
    		}
    	 } 
    
    	partial void Beforevalue_data_typeChange(int oldValue, int newValue);
    	partial void Aftervalue_data_typeChange(int oldValue, int newValue);
    
    	private string _description;
        public string description {
    		get { 
    			return _description;
    		} 
    		set {
    			if (value != _description){
    			    string old = _description;
    				BeforedescriptionChange(old, value);
    				_description = value;
    			    NotifyPropertyChanged("description");
    				AfterdescriptionChange(old, value);
    			}
    		}
    	 } 
    
    	partial void BeforedescriptionChange(string oldValue, string newValue);
    	partial void AfterdescriptionChange(string oldValue, string newValue);
    
    	private string _name;
        public string name {
    		get { 
    			return _name;
    		} 
    		set {
    			if (value != _name){
    			    string old = _name;
    				BeforenameChange(old, value);
    				_name = value;
    			    NotifyPropertyChanged("name");
    				AfternameChange(old, value);
    			}
    		}
    	 } 
    
    	partial void BeforenameChange(string oldValue, string newValue);
    	partial void AfternameChange(string oldValue, string newValue);
    
    
    	private ObservableCollection<plugin_setting_options> _plugin_setting_options;
        public virtual ObservableCollection<plugin_setting_options> plugin_setting_options {
    		get { 
    			return _plugin_setting_options;
    		} 
    		set {
    			if (value != _plugin_setting_options){
    			    ObservableCollection<plugin_setting_options> old = _plugin_setting_options;
    				Beforeplugin_setting_optionsChange(old, value);
    				_plugin_setting_options = value;
    			    NotifyPropertyChanged("plugin_setting_options");
    				Afterplugin_setting_optionsChange(old, value);
    			}
    		}
    	 } 
    
    	partial void Beforeplugin_setting_optionsChange(ObservableCollection<plugin_setting_options> oldValue, ObservableCollection<plugin_setting_options> newValue);
    	partial void Afterplugin_setting_optionsChange(ObservableCollection<plugin_setting_options> oldValue, ObservableCollection<plugin_setting_options> newValue);
    
    	private plugin _plugin;
        public virtual plugin plugin {
    		get { 
    			return _plugin;
    		} 
    		set {
    			if (value != _plugin){
    			    plugin old = _plugin;
    				BeforepluginChange(old, value);
    				_plugin = value;
    			    NotifyPropertyChanged("plugin");
    				AfterpluginChange(old, value);
    			}
    		}
    	 } 
    
    	partial void BeforepluginChange(plugin oldValue, plugin newValue);
    	partial void AfterpluginChange(plugin oldValue, plugin newValue);
    }
}
