//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zVirtualScenesModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class plugin_setting_options
    {
        public int id { get; set; }
        public int plugin_settings_id { get; set; }
        public string options { get; set; }
    
        public virtual plugin_settings plugin_settings { get; set; }
    }
}
