//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Collections.ObjectModel;

namespace zVirtualScenesModel
{
    
    public partial class plugin_setting_options : INotifyPropertyChanged
    {
    	public event PropertyChangedEventHandler PropertyChanged;
        protected void NotifyPropertyChanged(string name)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(name));
            }
        }
    
    
    	private int _id;
        public int id {
    		get { 
    			return _id;
    		} 
    		set {
    			if (value != _id){
    			    int old = _id;
    				BeforeidChange(old, value);
    				_id = value;
    			    NotifyPropertyChanged("id");
    				AfteridChange(old, value);
    			}
    		}
    	 } 
    
    	partial void BeforeidChange(int oldValue, int newValue);
    	partial void AfteridChange(int oldValue, int newValue);
    
    	private int _plugin_settings_id;
        public int plugin_settings_id {
    		get { 
    			return _plugin_settings_id;
    		} 
    		set {
    			if (value != _plugin_settings_id){
    			    int old = _plugin_settings_id;
    				Beforeplugin_settings_idChange(old, value);
    				_plugin_settings_id = value;
    			    NotifyPropertyChanged("plugin_settings_id");
    				Afterplugin_settings_idChange(old, value);
    			}
    		}
    	 } 
    
    	partial void Beforeplugin_settings_idChange(int oldValue, int newValue);
    	partial void Afterplugin_settings_idChange(int oldValue, int newValue);
    
    	private string _options;
        public string options {
    		get { 
    			return _options;
    		} 
    		set {
    			if (value != _options){
    			    string old = _options;
    				BeforeoptionsChange(old, value);
    				_options = value;
    			    NotifyPropertyChanged("options");
    				AfteroptionsChange(old, value);
    			}
    		}
    	 } 
    
    	partial void BeforeoptionsChange(string oldValue, string newValue);
    	partial void AfteroptionsChange(string oldValue, string newValue);
    
    
    	private plugin_settings _plugin_settings;
        public virtual plugin_settings plugin_settings {
    		get { 
    			return _plugin_settings;
    		} 
    		set {
    			if (value != _plugin_settings){
    			    plugin_settings old = _plugin_settings;
    				Beforeplugin_settingsChange(old, value);
    				_plugin_settings = value;
    			    NotifyPropertyChanged("plugin_settings");
    				Afterplugin_settingsChange(old, value);
    			}
    		}
    	 } 
    
    	partial void Beforeplugin_settingsChange(plugin_settings oldValue, plugin_settings newValue);
    	partial void Afterplugin_settingsChange(plugin_settings oldValue, plugin_settings newValue);
    }
}
