//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zvsModel
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    
    public partial class scene
    {
        public scene()
        {
            this.device_value_triggers = new ObservableCollection<device_value_triggers>();
            this.scene_commands = new ObservableCollection<scene_commands>();
            this.scene_property_value = new ObservableCollection<scene_property_value>();
        }
    
        public int id { get; set; }
        public string friendly_name { get; set; }
        public Nullable<int> sort_order { get; set; }
        public bool is_running { get; set; }
    
        public virtual ObservableCollection<device_value_triggers> device_value_triggers { get; set; }
        public virtual ObservableCollection<scene_commands> scene_commands { get; set; }
        public virtual ObservableCollection<scene_property_value> scene_property_value { get; set; }
    }
}
