//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zVirtualScenesModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class scene_commands
    {
        public int id { get; set; }
        public int scene_id { get; set; }
        public Nullable<int> device_id { get; set; }
        public int command_type_id { get; set; }
        public int command_id { get; set; }
        public string arg { get; set; }
        public Nullable<int> sort_order { get; set; }
    
        public virtual device device { get; set; }
        public virtual scene scene { get; set; }
    }
}
