//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zVirtualScenesModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zvsLocalDBEntities : DbContext
    {
        public zvsLocalDBEntities()
            : base("name=zvsLocalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<builtin_command_options> builtin_command_options { get; set; }
        public DbSet<builtin_command_que> builtin_command_que { get; set; }
        public DbSet<builtin_commands> builtin_commands { get; set; }
        public DbSet<db_info> db_info { get; set; }
        public DbSet<device_command_options> device_command_options { get; set; }
        public DbSet<device_command_que> device_command_que { get; set; }
        public DbSet<device_commands> device_commands { get; set; }
        public DbSet<device_property_options> device_property_options { get; set; }
        public DbSet<device_property_values> device_property_values { get; set; }
        public DbSet<device_propertys> device_propertys { get; set; }
        public DbSet<device_type_command_options> device_type_command_options { get; set; }
        public DbSet<device_type_command_que> device_type_command_que { get; set; }
        public DbSet<device_type_commands> device_type_commands { get; set; }
        public DbSet<device_types> device_types { get; set; }
        public DbSet<device_value_triggers> device_value_triggers { get; set; }
        public DbSet<device_values> device_values { get; set; }
        public DbSet<device> devices { get; set; }
        public DbSet<group_devices> group_devices { get; set; }
        public DbSet<group> groups { get; set; }
        public DbSet<plugin_setting_options> plugin_setting_options { get; set; }
        public DbSet<plugin_settings> plugin_settings { get; set; }
        public DbSet<plugin> plugins { get; set; }
        public DbSet<program_options> program_options { get; set; }
        public DbSet<scene_commands> scene_commands { get; set; }
        public DbSet<scene_property> scene_property { get; set; }
        public DbSet<scene_property_option> scene_property_option { get; set; }
        public DbSet<scene_property_value> scene_property_value { get; set; }
        public DbSet<scene> scenes { get; set; }
        public DbSet<scheduled_tasks> scheduled_tasks { get; set; }
        public DbSet<javascript_triggers> javascript_triggers { get; set; }
    }
}
